name: Legacy Pages Workflow

on:
  workflow_dispatch:

jobs:
  noop:
    runs-on: ubuntu-latest

    steps:
      - name: Legacy Workflow Disabled
        run: echo "Use .github/workflows/deploy.yml instead."
